// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

export { }
